### ISSUE TITLE
Spent 6 hours to make it run

### ISSUE THREAD

**Issue by chmod777john** [ShaoX96/ChemPlasKin#1]
6 hours ago i tried to run this project. 
Guessing all the undocumented details, configuring the environment, etc

I found you updated the repo few minutes ago. Much details added, which I have spent much time to figure out.

I suggest to use the github codespace + devcontainer. Basically it is a virtual environment, you write a configure file so that when people open a codespace, all the requirement will be satisfied. No need to manually `mv` or `cp` files. All will be done automatically.

**Comment by chmod777john** [comment]
And how about we create a real-time chatting group? We can discuss in that group.

**Comment by ShaoX96** [comment]
Hope the update makes things clear. Thank you for the suggestion and I'll think about it.  The major difficulty is that I'm super busy with other projects, making code maintenance and technical support challenging. I may make few Youtube videos of instruction in the near future.

**Comment by chmod777john** [comment]
Ok, I will create Pull Request, to make the project easier to start.
